amp: false
batch_size: 3000
bert: xlm-roberta-large
bert_pad_index: null
bert_pooling: mean
binarize: false
bos_index: 0
buckets: 32
build: true
cache: false
char_pad_index: null
checkpoint: false
clip: 5.0
dev: /home/hairmore/Desktop/parser-main/dataset_conllu/train/NXD_data/devNXD.conllu
device: '0'
dist: ddp
embed: glove-6b-100
encoder: bert
encoder_dropout: 0.1
epochs: 5
even: false
feat: null
fix_len: 20
local_rank: 0
lr: 5.0e-05
lr_rate: 20
max_len: null
min_freq: 2
mix_dropout: 0.0
mlp_dropout: 0.33
mode: train
n_arc_mlp: 500
n_bert_layers: 4
n_chars: null
n_rel_mlp: 100
n_rels: 49
n_tags: null
n_words: 250002
pad_index: 1
partial: false
path: modelNXD5
patience: 100
proj: false
punct: false
seed: 1
steps: 2162
test: /home/hairmore/Desktop/parser-main/dataset_conllu/train/NXD_data/testNXD.conllu
threads: 16
train: /home/hairmore/Desktop/parser-main/dataset_conllu/train/NXD_data/trainNXD.conllu
tree: false
unk_index: 3
update_steps: 4
verbose: true
wandb: false
warmup: 0.1
workers: 0
